### ISSUE TITLE
Create New UI for ChitChat

### ISSUE THREAD

**Issue by OshadhaVimuB** [OshadhaVimuB/ChitChat#1]
The current UI of the ChitChat application could benefit from a redesign to enhance user experience and overall aesthetics. A fresh and modern interface would make the application more appealing and user-friendly.

Objectives:

- Redesign the chat interface for better usability.
- Update the color scheme to make it more vibrant and inviting.
- Improve the layout for better organization of chat messages and user interactions.
- Ensure the new design is responsive and works well on various screen sizes.

Requirements:

Remove the send button and add a send icon.

**Comment by ViuslaS16** [comment]
I will take over the UI redesign for ChitChat. Can you please clarify your requirements accurately? Asign it.

**Comment by eqn-group** [comment]
> I will take over the UI redesign for ChitChat. Can you please clarify your requirements accurately? Asign it.

![image](https://github.com/user-attachments/assets/c9b9cbbc-2ccb-444b-b13a-930241d23ce1)

use this icon

**Comment by iitzIrFan** [comment]
I can work on this issue as I had worked on such python projects so assign this to me as I feel am the right person you can work with...

**Comment by iitzIrFan** [comment]
Demo of my work 
![Screenshot 2024-10-11 002630](https://github.com/user-attachments/assets/1116448e-f866-4c58-b92b-4d54f8658071)
![Screenshot 2024-10-11 002700](https://github.com/user-attachments/assets/ea967968-9e03-4b69-8467-3dd87c62ca6e)

**Comment by OshadhaVimuB** [comment]
I assigned it to you. So now you can work on this

**Comment by iitzIrFan** [comment]
How is my demo work and any inputs from your side?

**Comment by OshadhaVimuB** [comment]
I like to remove the send button and add an icon for it

**Comment by iitzIrFan** [comment]
Can you feel free to choose any of the following images from this :- https://www.flaticon.com/free-icons/send
or we can move to some other asper your choice

**Comment by iitzIrFan** [comment]
Is this right 
![Screenshot 2024-10-11 005057](https://github.com/user-attachments/assets/4521c11d-f307-4821-b8dc-14b979f7ed39)
![Screenshot 2024-10-11 005125](https://github.com/user-attachments/assets/78c64f6f-3032-49f2-a048-6b777c556d0f)

**Comment by OshadhaVimuB** [comment]
![App](https://github.com/user-attachments/assets/c5dc2c83-5c6a-4264-a4b3-284f07daa966)

This is the UI I'm trying to build. You can try to implement things in this image

**Comment by iitzIrFan** [comment]
Only frontend part of buttons and other parts are you talking about ?

**Comment by OshadhaVimuB** [comment]
yeah only frontend

**Comment by iitzIrFan** [comment]
![Screenshot 2024-10-11 021643](https://github.com/user-attachments/assets/d1736ebe-e1a6-4235-992b-63a294ecb8d3)

**Comment by iitzIrFan** [comment]
Check this one !!!

**Comment by mahenoorsalat** [comment]
@OshadhaVimuB  I want to work on ui thing .. can you please me this issue ..? looking forward to your response

**Comment by OshadhaVimuB** [comment]
@mahenoorsalat I'll assign you too.

**Comment by iitzIrFan** [comment]
Should I make a pr request then?

**Comment by OshadhaVimuB** [comment]
@iitzIrFan sure

**Comment by iitzIrFan** [comment]
@OshadhaVimuB  I have created my PR req so do merge it in your code.

**Comment by mahenoorsalat** [comment]
Thank you @OshadhaVimuB  :)
