### ISSUE TITLE
DOCUMENTATION UPGRADATION AND ENHANCEMENT

### ISSUE THREAD

**Issue by Naren456** [OshadhaVimuB/ChitChat#14]
I'd like to add more tutorials and images to your documentation , so that it becomes more engaging and readable.
please assign me hacktober fest label

**Comment by OshadhaVimuB** [comment]
@Naren456 done

**Comment by OshadhaVimuB** [comment]
@Naren456 Could you please confirm whether you will be handling this matter, or if I should assign it to someone else?

**Comment by Naren456** [comment]
Assign to someone .

**Comment by Moses-Mk** [comment]
Please assign this issue to me. Thanks
