### ISSUE TITLE
Fix the top margin

### ISSUE THREAD

**Issue by OshadhaVimuB** [OshadhaVimuB/ChitChat#17]
Add a top margin to the app

**Comment by shiv-0101** [comment]
possible if you could share a screenshot?

**Comment by kiinshuk** [comment]
Hi @OshadhaVimuB  , I'd like to help with this issue. Could you please assign it to me?

**Comment by OshadhaVimuB** [comment]
@kiinshuk done

**Comment by kiinshuk** [comment]
@OshadhaVimuB please check pull request

**Comment by OshadhaVimuB** [comment]
Okay give me few minutes
