### ISSUE TITLE
Improve Documentation for ChitChat

### ISSUE THREAD

**Issue by OshadhaVimuB** [OshadhaVimuB/ChitChat#2]
The documentation for the ChitChat application needs to be updated and streamlined to help users and contributors better understand the project.

### Objectives:

- Update the README with clear installation and usage instructions.

### Acceptance Criteria:

- A revised README that includes all necessary sections.

**Comment by UmeshIsu** [comment]
I can go through this issue. Assign me

**Comment by OshadhaVimuB** [comment]
Sure.
