### ISSUE TITLE
Add Sign-Up and Login Functionality

### ISSUE THREAD

**Issue by OshadhaVimuB** [OshadhaVimuB/ChitChat#8]
### Description:

To enhance the user experience and security of the ChitChat application, we need to implement a sign-up and login feature. This will allow users to create accounts, securely log in, and manage their chat sessions.

### Objectives:

- Add a sign-up page where users can create an account with a username and password.
- Implement a login page to allow users to authenticate using their credentials.
- Securely store user information using proper encryption techniques.
- Ensure the app restricts chat access to logged-in users only.

### Requirements:

- Ensure password security with hashing.
- Provide proper form validation for inputs.
- Maintain a session after login to keep users authenticated.

### Acceptance Criteria:

- Working sign-up and login functionality integrated into the ChitChat app.
- Proper error handling for invalid login attempts or registration issues.
- Logged-in users are able to access the chat, while non-logged-in users are restricted.

Feel free to ask any questions if needed!

**Comment by Abhilash-0322** [comment]
I would like to work on this issue

**Comment by naitik-2006** [comment]
I would like to work on this issue 
I have already done the similar work, you can view here :-  https://github.com/naitik-2006/enjoy-school/blob/main/enjoy-school-demo%20(1).mp4
Please assign me this issue

**Comment by Sidratul02** [comment]
@OshadhaVimuB could you please assign me this issue.

**Comment by OshadhaVimuB** [comment]
@naitik-2006 done
